### ISSUE TITLE
max_overlap_ratio=0.3 and still duplicate sentences from original source

### ISSUE THREAD

**Issue by seuaCoder** [jsvine/markovify#119] opened 2019-12-08 07:02 UTC
I'm trying to generate unique sentences from a text source. I set max_overlap_ratio to 0.3 and i still have sentences that matches exactly some sentences from the original text.

How to avoid that ?

**Comment by seuaCoder** [comment] 2019-12-08 08:20
My source text contain 30 000 words. What would be the settings to generate unique sentences from this source ?

**Comment by seuaCoder** [comment] 2019-12-09 06:32
I adjusted state_size=1 and i have no more duplicate. How does the state size influence the results ?

**Comment by jsvine** [comment] 2019-12-10 13:48
To debug this issue, it would be helpful if you could provide a reproducible example — the corpus and a script that demonstrates the problem. If there's not a bug in the `markovify` code, one possibility is that there's something unusual in the way the corpus is formatted. But that's just a guess; hard to say for sure without seeing it.

**Comment by seuaCoder** [comment] 2019-12-10 13:58
This is the corpus : https://pastebin.com/C6G7FZ2x

```
text_model = markovify.Text(data["data"]["text"])
text_model.make_sentence(max_overlap_ratio=0.3, tries=1000)
```

**Comment by jsvine** [comment] 2019-12-12 13:54
Hi @seuaCoder. When I run the code below, I do not detect the problem with reproducing original text. 

```python
#!/usr/bin/env python

import markovify

corpus = open("pastebin.txt").read() # This is the file you linked to above
text_model = markovify.Text(corpus)

for i in range(1000):
    sent = text_model.make_sentence(max_overlap_ratio=0.3, tries=1000)
    if sent is not None and sent in corpus:
        print(sent)
```

It’s possible that some of what you’re seeing *looks* like text from the original, but is actually slightly different. In that case, I’d recommend writing your own filter for what “counts” as too close to the original. Closing this issue for now. If you’re able to provide a script that demonstrates the problem more explicitly, feel free to reopen.

**Closed by jsvine** 2019-12-12 13:54 UTC

**Comment by seuaCoder** [comment] 2019-12-13 08:03
Hi @jsvine,

I did a test with exactly the same code as above (yours) and the same corpus. I'm still finding some sequences of 3, 4 (or more) words which match exactly some sequences in the corpus. I now believe that this is normal. Howeven with state_size=1 there are no duplicated sequences of words.

Could you please tell me how state_size can influence the final results ? Why i don''t have duplicate with state_size=1 but i have many with state_size=2 ? 

Thank you !

**Comment by seuaCoder** [comment] 2019-12-18 13:40
Hi, this has been closed without beeing resolved. Is it possible to have a reply ?
